#define SOLARUS_MAJOR_VERSION 1
#define SOLARUS_MINOR_VERSION 7
#define SOLARUS_PATCH_VERSION 0

#define SOLARUS_GIT_REVISION "1.7"

//#define SOLARUS_HAVE_OPENGL 1
//#define SOLARUS_HAVE_MKSTEMP 0
#define SOLARUS_HAVE_UNISTD_H 1
